ENCRYPTION_ON = 1
ENCRYPTION_OFF = 2
JOIN = 3
LEAVE = 4
REGISTER = 5
LOGIN = 6
LOGOUT = 7
USERLIST = 8
MESSAGE = 9
DATE = 10
TIME = 11
QUOTE_OF_THE_DAY = 101
QUOTE_OF_THE_MOMENT = 102
WORD_OF_THE_DAY = 103
WORD_OF_THE_MOMENT = 104
MATH_PROBLEM_OF_THE_DAY = 105
MATH_PROBLEM_OF_THE_MOMENT = 106
MATH_THEOREM_OF_THE_DAY = 107
MATH_THEOREM_OF_THE_MOMENT = 108
CHESS_GAME_OF_THE_DAY = 109
CHESS_GAME_OF_THE_MOMENT = 110
CHESS_PUZZLE_OF_THE_DAY = 111
CHESS_PUZZLE_OF_THE_MOMENT = 112

map = {
    1: "ENCRYPTION_ON",
    2: "ENCRYPTION_OFF",
    3: "JOIN",
    4: "LEAVE",
    5: "REGISTER",
    6: "LOGIN",
    7: "LOGOUT",
    8: "USERLIST",
    9: "MESSAGE",
    10: "DATE",
    11: "TIME",
    101: "QUOTE_OF_THE_DAY",
    102: "QUOTE_OF_THE_MOMENT",
    103: "WORD_OF_THE_DAY",
    104: "WORD_OF_THE_MOMENT",
    105: "MATH_PROBLEM_OF_THE_DAY",
    106: "MATH_PROBLEM_OF_THE_MOMENT",
    107: "MATH_THEOREM_OF_THE_DAY",
    108: "MATH_THEOREM_OF_THE_MOMENT",
    109: "CHESS_GAME_OF_THE_DAY",
    110: "CHESS_GAME_OF_THE_MOMENT",
    111: "CHESS_PUZZLE_OF_THE_DAY",
    112: "CHESS_PUZZLE_OF_THE_MOMENT"
}
