EXCHANGE_PUBLIC_KEY = 10
REGISTER = 11
LOGIN = 12
LOGOUT = 13
MESSAGE = 14

DATE = 20
DATETIME = 21
TIME = 22

QUOTE_OF_THE_DAY = 30
QUOTE_OF_THE_MOMENT = 31
WORD_OF_THE_DAY = 32
WORD_OF_THE_MOMENT = 33

MATH_PROBLEM_OF_THE_DAY = 40
MATH_PROBLEM_OF_THE_MOMENT = 41
MATH_THEOREM_OF_THE_DAY = 42
MATH_THEOREM_OF_THE_MOMENT = 43

CHESS_GAME_OF_THE_DAY = 50
CHESS_GAME_OF_THE_MOMENT = 51
CHESS_PUZZLE_OF_THE_DAY = 52
CHESS_PUZZLE_OF_THE_MOMENT = 53
